#= require jquery
# require jquery_ujs
# require turbolinks
#= require angular/angular.min.js
# require sifter
# require microplugin
# require selectize
#= require jquery.tagsinput/src/jquery.tagsinput.js
# require_tree .
